package com.factory.management.service.ServiceImpl;
import com.factory.management.dto.request.FinancialCategoryRequest;import com.factory.management.dto.response.FinancialCategoryResponse;import com.factory.management.entity.*;import com.factory.management.exception.*;import com.factory.management.repository.FinancialCategoryRepository;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;
@Service @RequiredArgsConstructor public class FinancialCategoryService{private final FinancialCategoryRepository repository;
 @Transactional public FinancialCategoryResponse create(FinancialCategoryRequest r){String code=r.getCode().trim().toUpperCase();if(repository.existsByCodeIgnoreCase(code))throw new AppException(ErrorCode.FINANCIAL_CATEGORY_CODE_EXISTS);validate(r);return response(repository.save(entity(new FinancialCategory(),r,code)));}
 @Transactional(readOnly=true)public List<FinancialCategoryResponse> all(){return repository.findAllByActiveTrueOrderByCode().stream().map(this::response).toList();}
 @Transactional public FinancialCategoryResponse update(Long id,FinancialCategoryRequest r){FinancialCategory v=find(id);String code=r.getCode().trim().toUpperCase();if(repository.existsByCodeIgnoreCaseAndIdNot(code,id))throw new AppException(ErrorCode.FINANCIAL_CATEGORY_CODE_EXISTS);validate(r);return response(entity(v,r,code));}
 @Transactional public void delete(Long id){find(id).setActive(false);}
 private void validate(FinancialCategoryRequest r){if(r.getEntryType()==FinancialEntryType.REVENUE&&r.getExpenseGroup()!=null)throw new AppException(ErrorCode.INVALID_FINANCIAL_CATEGORY_TYPE);}
 private FinancialCategory entity(FinancialCategory v,FinancialCategoryRequest r,String code){v.setCode(code);v.setName(r.getName().trim());v.setEntryType(r.getEntryType());v.setExpenseGroup(r.getEntryType()==FinancialEntryType.EXPENSE?r.getExpenseGroup():null);v.setDescription(r.getDescription());if(r.getActive()!=null)v.setActive(r.getActive());return v;}
 private FinancialCategory find(Long id){return repository.findById(id).orElseThrow(()->new AppException(ErrorCode.FINANCIAL_CATEGORY_NOT_FOUND));}
 private FinancialCategoryResponse response(FinancialCategory v){return FinancialCategoryResponse.builder().id(v.getId()).code(v.getCode()).name(v.getName()).entryType(v.getEntryType()).expenseGroup(v.getExpenseGroup()).description(v.getDescription()).active(v.getActive()).build();}}
