package com.factory.management.service.ServiceImpl;
import com.factory.management.dto.response.*;import com.factory.management.entity.*;import com.factory.management.exception.*;import com.factory.management.mapper.ProductionReportMapper;import com.factory.management.repository.*;import com.factory.management.service.Service.ProductionReportDetailService;import lombok.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class ProductionReportDetailServiceImpl implements ProductionReportDetailService {
 private final ProductionReportRepository reportRepository;private final MachineDowntimeRepository downtimeRepository;private final QualityReportRepository qualityRepository;private final MaterialIssueRepository materialRepository;private final EmployeeActualRepository employeeRepository;private final ProductionReportMapper mapper;
 @Override @Transactional(readOnly=true) public ProductionReportDetailResponse getByReportId(Long id){ProductionReport report=reportRepository.findById(id).orElseThrow(()->new AppException(ErrorCode.PRODUCTION_REPORT_NOT_FOUND));return ProductionReportDetailResponse.builder().report(mapper.mapToResponse(report))
 .downtimes(downtimeRepository.findAllByProductionReport_Id(id).stream().map(x->ProductionReportDetailResponse.DowntimeItem.builder().id(x.getId()).machineId(x.getMachine().getId()).machineCode(x.getMachine().getCode()).downtimeReasonId(x.getDowntimeReason().getId()).downtimeReasonName(x.getDowntimeReason().getName()).startTime(x.getStartTime()).endTime(x.getEndTime()).durationMinutes(x.getDurationMinutes()).description(x.getDescription()).build()).toList())
 .qualityErrors(qualityRepository.findAllByProductionReport_Id(id).stream().map(x->ProductionReportDetailResponse.QualityItem.builder().id(x.getId()).qualityErrorTypeId(x.getQualityErrorType().getId()).qualityErrorTypeName(x.getQualityErrorType().getName()).quantity(x.getQuantity()).description(x.getDescription()).build()).toList())
 .materialIssues(materialRepository.findAllByProductionReport_Id(id).stream().map(x->ProductionReportDetailResponse.MaterialItem.builder().id(x.getId()).materialId(x.getMaterial().getId()).materialName(x.getMaterial().getName()).issueType(x.getIssueType()).quantity(x.getQuantity()).unit(x.getUnit()).description(x.getDescription()).build()).toList())
 .employees(employeeRepository.findAllByProductionReport_Id(id).stream().map(x->ProductionReportDetailResponse.EmployeeItem.builder().id(x.getId()).employeeId(x.getEmployee().getId()).employeeCode(x.getEmployee().getCode()).employeeName(x.getEmployee().getFullName()).workingMinutes(x.getWorkingMinutes()).overtimeMinutes(x.getOvertimeMinutes()).attendanceStatus(x.getAttendanceStatus()).assignmentType(x.getAssignmentType()).description(x.getDescription()).build()).toList()).build();}
}
