package com.factory.management.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "Lỗi không xác định", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(1000, "Khóa không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_FACTORY_CODE(1001, "Mã xưởng không hợp lệ", HttpStatus.BAD_REQUEST),
    NOT_BLANK_FACTORY_CODE(1002, "Mã xưởng không được trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_FACTORY_NAME(1003, "Tên xưởng không được trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_FACTORY_ADDRESS(1004, "Địa chỉ xưởng không được trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_FACTORY_ACTIVE(1005, "Trạng thái xưởng không được trống", HttpStatus.BAD_REQUEST),
    SIZE_FACTORY_CODE(1006, "Mã nhà máy không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    FACTORY_CODE_EXISTS(1007, "Mã xưởng đã tồn tại", HttpStatus.BAD_REQUEST),
    FACTORY_ID_NOT_FOUND(1008, "Mã xưởng không tồn tại", HttpStatus.NOT_FOUND),
    SIZE_FACTORY_NAME(1009, "Tên xưởng không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_FACTORY_ADDRESS(1010, "Địa chỉ xưởng không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_DEPARTMENT_FACTORY_ID(1011, "Nhà máy của phòng ban không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_DEPARTMENT_CODE(1012, "Mã phòng ban không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_DEPARTMENT_CODE(1013, "Mã phòng ban không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_DEPARTMENT_NAME(1014, "Tên phòng ban không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_DEPARTMENT_NAME(1015, "Tên phòng ban không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_DEPARTMENT_DESCRIPTION(1016, "Mô tả phòng ban không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    DEPARTMENT_CODE_EXISTS(1017, "Mã phòng ban đã tồn tại trong nhà máy", HttpStatus.BAD_REQUEST),
    DEPARTMENT_ID_NOT_FOUND(1018, "Phòng ban không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_PRODUCTION_LINE_DEPARTMENT_ID(1019, "Phòng ban của dây chuyền không được để trống",
            HttpStatus.BAD_REQUEST),
    NOT_BLANK_PRODUCTION_LINE_CODE(1020, "Mã dây chuyền không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_PRODUCTION_LINE_CODE(1021, "Mã dây chuyền không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_PRODUCTION_LINE_NAME(1022, "Tên dây chuyền không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_PRODUCTION_LINE_NAME(1023, "Tên dây chuyền không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_PRODUCTION_LINE_DESCRIPTION(1024, "Mô tả dây chuyền không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    PRODUCTION_LINE_CODE_EXISTS(1025, "Mã dây chuyền đã tồn tại trong phòng ban", HttpStatus.BAD_REQUEST),
    PRODUCTION_LINE_ID_NOT_FOUND(1026, "Dây chuyền sản xuất không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_TEAM_PRODUCTION_LINE_ID(1027, "Dây chuyền của Team không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_TEAM_CODE(1028, "Mã Team không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_TEAM_CODE(1029, "Mã Team không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_TEAM_NAME(1030, "Tên Team không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_TEAM_NAME(1031, "Tên Team không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_TEAM_DESCRIPTION(1032, "Mô tả Team không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    TEAM_CODE_EXISTS(1033, "Mã Team đã tồn tại trong dây chuyền", HttpStatus.BAD_REQUEST),
    TEAM_ID_NOT_FOUND(1034, "Team không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_EMPLOYEE_TEAM_ID(1035, "Team của nhân viên không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_EMPLOYEE_CODE(1036, "Mã nhân viên không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_EMPLOYEE_CODE(1037, "Mã nhân viên không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_EMPLOYEE_FULL_NAME(1038, "Họ tên nhân viên không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_EMPLOYEE_FULL_NAME(1039, "Họ tên nhân viên không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_EMPLOYEE_POSITION(1040, "Chức vụ nhân viên không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_EMPLOYEE_POSITION(1041, "Chức vụ nhân viên không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_EMPLOYEE_HIRE_DATE(1042, "Ngày vào làm không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_EMPLOYEE_HIRE_DATE(1043, "Ngày vào làm không được ở tương lai", HttpStatus.BAD_REQUEST),
    EMPLOYEE_CODE_EXISTS(1044, "Mã nhân viên đã tồn tại", HttpStatus.BAD_REQUEST),
    EMPLOYEE_ID_NOT_FOUND(1045, "Nhân viên không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_TEAM_LEADER_EMPLOYEE_ID(1046, "Nhân viên leader không được để trống", HttpStatus.BAD_REQUEST),
    TEAM_LEADER_NOT_MEMBER(1047, "Leader phải là nhân viên thuộc chính Team này", HttpStatus.BAD_REQUEST),
    NOT_BLANK_SHIFT_CODE(1048, "Mã ca làm việc không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_SHIFT_CODE(1049, "Mã ca làm việc không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_SHIFT_NAME(1050, "Tên ca làm việc không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_SHIFT_NAME(1051, "Tên ca làm việc không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_SHIFT_START_TIME(1052, "Giờ bắt đầu không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_SHIFT_END_TIME(1053, "Giờ kết thúc không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_SHIFT_TIME_RANGE(1054, "Giờ bắt đầu và giờ kết thúc không được trùng nhau", HttpStatus.BAD_REQUEST),
    SHIFT_CODE_EXISTS(1055, "Mã ca làm việc đã tồn tại", HttpStatus.BAD_REQUEST),
    SHIFT_ID_NOT_FOUND(1056, "Ca làm việc không tồn tại", HttpStatus.NOT_FOUND),
    NOT_BLANK_MACHINE_TYPE_CODE(1057, "Mã loại máy không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MACHINE_TYPE_CODE(1058, "Mã loại máy không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MACHINE_TYPE_NAME(1059, "Tên loại máy không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MACHINE_TYPE_NAME(1060, "Tên loại máy không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_MACHINE_TYPE_DESCRIPTION(1061, "Mô tả loại máy không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    MACHINE_TYPE_CODE_EXISTS(1062, "Mã loại máy đã tồn tại", HttpStatus.BAD_REQUEST),
    MACHINE_TYPE_ID_NOT_FOUND(1063, "Loại máy không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_MACHINE_TYPE_ID(1064, "Loại máy không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MACHINE_TEAM_ID(1065, "Team quản lý máy không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MACHINE_CODE(1066, "Mã máy không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MACHINE_CODE(1067, "Mã máy không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MACHINE_NAME(1068, "Tên máy không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MACHINE_NAME(1069, "Tên máy không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_MACHINE_DESCRIPTION(1070, "Mô tả máy không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    MACHINE_CODE_EXISTS(1071, "Mã máy đã tồn tại", HttpStatus.BAD_REQUEST),
    MACHINE_ID_NOT_FOUND(1072, "Máy không tồn tại", HttpStatus.NOT_FOUND),
    NOT_BLANK_DOWNTIME_REASON_CODE(1073, "Mã lý do dừng máy không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_DOWNTIME_REASON_CODE(1074, "Mã lý do dừng máy không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_DOWNTIME_REASON_NAME(1075, "Tên lý do dừng máy không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_DOWNTIME_REASON_NAME(1076, "Tên lý do dừng máy không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_DOWNTIME_REASON_DESCRIPTION(1077, "Mô tả lý do dừng máy không được vượt quá 500 ký tự",
            HttpStatus.BAD_REQUEST),
    DOWNTIME_REASON_CODE_EXISTS(1078, "Mã lý do dừng máy đã tồn tại", HttpStatus.BAD_REQUEST),
    DOWNTIME_REASON_ID_NOT_FOUND(1079, "Lý do dừng máy không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_DOWNTIME_REASON_TYPE(1080, "Loại lý do dừng máy không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_QUALITY_ERROR_TYPE_CODE(1081, "Mã loại lỗi chất lượng không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_QUALITY_ERROR_TYPE_CODE(1082, "Mã loại lỗi chất lượng không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_QUALITY_ERROR_TYPE_NAME(1083, "Tên loại lỗi chất lượng không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_QUALITY_ERROR_TYPE_NAME(1084, "Tên loại lỗi chất lượng không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_QUALITY_ERROR_TYPE_DESCRIPTION(1085, "Mô tả loại lỗi chất lượng không được vượt quá 500 ký tự",
            HttpStatus.BAD_REQUEST),
    NOT_NULL_QUALITY_ERROR_TYPE_SEVERITY(1086, "Mức độ nghiêm trọng không được để trống", HttpStatus.BAD_REQUEST),
    QUALITY_ERROR_TYPE_CODE_EXISTS(1087, "Mã loại lỗi chất lượng đã tồn tại", HttpStatus.BAD_REQUEST),
    QUALITY_ERROR_TYPE_ID_NOT_FOUND(1088, "Loại lỗi chất lượng không tồn tại", HttpStatus.NOT_FOUND),
    NOT_BLANK_MATERIAL_CODE(1089, "Mã nguyên vật liệu không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MATERIAL_CODE(1090, "Mã nguyên vật liệu không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MATERIAL_NAME(1091, "Tên nguyên vật liệu không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MATERIAL_NAME(1092, "Tên nguyên vật liệu không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MATERIAL_UNIT(1093, "Đơn vị tính không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MATERIAL_UNIT(1094, "Đơn vị tính không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_MATERIAL_DESCRIPTION(1095, "Mô tả nguyên vật liệu không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    MATERIAL_CODE_EXISTS(1096, "Mã nguyên vật liệu đã tồn tại", HttpStatus.BAD_REQUEST),
    MATERIAL_ID_NOT_FOUND(1097, "Nguyên vật liệu không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_REPORT_DATE(1098, "Ngày báo cáo không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_SHIFT_ID(1099, "Ca làm việc không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_FACTORY_ID(1100, "Nhà máy không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_DEPARTMENT_ID(1101, "Phòng ban không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_PRODUCTION_LINE_ID(1102, "Dây chuyền không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_TEAM_ID(1103, "Team không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_LEADER_ID(1104, "Người phụ trách không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_REPORT_MACHINE_ID(1105, "Máy không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_PLANNED_QUANTITY(1106, "Sản lượng kế hoạch không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_ACTUAL_QUANTITY(1107, "Sản lượng thực tế không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_DEFECT_QUANTITY(1108, "Sản lượng lỗi không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_WORKING_MINUTES(1109, "Số phút làm việc không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_DOWNTIME_MINUTES(1110, "Số phút dừng máy không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_REPORT_QUANTITY(1111, "Sản lượng không được âm", HttpStatus.BAD_REQUEST),
    INVALID_REPORT_MINUTES(1112, "Số phút không được âm", HttpStatus.BAD_REQUEST),
    SIZE_REPORT_NOTE(1113, "Ghi chú không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    REPORT_DEFECT_EXCEEDS_ACTUAL(1114, "Sản lượng lỗi không được lớn hơn sản lượng thực tế", HttpStatus.BAD_REQUEST),
    REPORT_DOWNTIME_EXCEEDS_WORKING(1115, "Phút dừng máy không được lớn hơn phút làm việc", HttpStatus.BAD_REQUEST),
    INVALID_REPORT_ORGANIZATION(1116,
            "Dữ liệu nhà máy, phòng ban, dây chuyền, Team, nhân viên hoặc máy không khớp nhau", HttpStatus.BAD_REQUEST),
    PRODUCTION_REPORT_STAGING_EXISTS(1117, "Báo cáo của ngày, ca, Team và máy này đã tồn tại", HttpStatus.BAD_REQUEST),
    PRODUCTION_REPORT_STAGING_NOT_FOUND(1118, "Báo cáo sản xuất tạm không tồn tại", HttpStatus.NOT_FOUND),
    INVALID_REPORT_STATUS_TRANSITION(1119, "Không thể thực hiện thao tác với trạng thái báo cáo hiện tại",
            HttpStatus.BAD_REQUEST),
    NOT_NULL_DOWNTIME_REPORT_ID(1120, "Báo cáo sản xuất tạm không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_DOWNTIME_MACHINE_ID(1121, "Máy dừng không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_DOWNTIME_REASON_ID(1122, "Lý do dừng máy không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_DOWNTIME_START_TIME(1123, "Thời điểm bắt đầu dừng không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_DOWNTIME_END_TIME(1124, "Thời điểm kết thúc dừng không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_DOWNTIME_DESCRIPTION(1125, "Mô tả dừng máy không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    INVALID_DOWNTIME_TIME_RANGE(1126, "Thời điểm kết thúc phải sau thời điểm bắt đầu ít nhất một phút",
            HttpStatus.BAD_REQUEST),
    MACHINE_DOWNTIME_REPORT_LOCKED(1127, "Không thể thay đổi downtime của báo cáo đã phê duyệt hoặc khóa",
            HttpStatus.BAD_REQUEST),
    MACHINE_DOWNTIME_MACHINE_MISMATCH(1128, "Máy dừng phải trùng với máy của báo cáo sản xuất tạm",
            HttpStatus.BAD_REQUEST),
    MACHINE_DOWNTIME_STAGING_NOT_FOUND(1129, "Dữ liệu dừng máy tạm không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_QUALITY_REPORT_ID(1130, "Báo cáo sản xuất tạm không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_QUALITY_ERROR_TYPE_ID(1131, "Loại lỗi chất lượng không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_QUALITY_QUANTITY(1132, "Số lượng lỗi không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_QUALITY_QUANTITY(1133, "Số lượng lỗi phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    SIZE_QUALITY_DESCRIPTION(1134, "Mô tả lỗi chất lượng không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    QUALITY_REPORT_PARENT_LOCKED(1135, "Không thể thay đổi lỗi của báo cáo đã phê duyệt hoặc khóa",
            HttpStatus.BAD_REQUEST),
    QUALITY_TOTAL_EXCEEDS_REPORT_DEFECT(1136, "Tổng lỗi chi tiết không được vượt sản lượng lỗi của báo cáo",
            HttpStatus.BAD_REQUEST),
    QUALITY_REPORT_STAGING_EXISTS(1137, "Loại lỗi này đã tồn tại trong báo cáo", HttpStatus.BAD_REQUEST),
    QUALITY_REPORT_STAGING_NOT_FOUND(1138, "Dữ liệu lỗi chất lượng tạm không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_MATERIAL_ISSUE_REPORT_ID(1139, "Báo cáo sản xuất tạm không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MATERIAL_ISSUE_MATERIAL_ID(1140, "Nguyên vật liệu không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MATERIAL_ISSUE_TYPE(1141, "Loại sự cố vật tư không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MATERIAL_ISSUE_QUANTITY(1142, "Số lượng vật tư sự cố không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_MATERIAL_ISSUE_QUANTITY(1143, "Số lượng vật tư sự cố phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MATERIAL_ISSUE_UNIT(1144, "Đơn vị tính không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MATERIAL_ISSUE_UNIT(1145, "Đơn vị tính không được vượt quá 50 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_MATERIAL_ISSUE_DESCRIPTION(1146, "Mô tả sự cố vật tư không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    MATERIAL_ISSUE_REPORT_LOCKED(1147, "Không thể thay đổi sự cố vật tư của báo cáo đã phê duyệt hoặc khóa",
            HttpStatus.BAD_REQUEST),
    MATERIAL_ISSUE_STAGING_NOT_FOUND(1148, "Dữ liệu sự cố vật tư tạm không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_EMPLOYEE_ACTUAL_REPORT_ID(1149, "Báo cáo sản xuất tạm không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_EMPLOYEE_ACTUAL_EMPLOYEE_ID(1150, "Nhân viên không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_EMPLOYEE_ACTUAL_WORKING_MINUTES(1151, "Phút làm việc không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_EMPLOYEE_ACTUAL_OVERTIME_MINUTES(1152, "Phút tăng ca không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_EMPLOYEE_ACTUAL_MINUTES(1153, "Phút làm việc và tăng ca không được âm", HttpStatus.BAD_REQUEST),
    NOT_NULL_ATTENDANCE_STATUS(1154, "Trạng thái có mặt không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_ASSIGNMENT_TYPE(1155, "Kiểu phân công không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_EMPLOYEE_ACTUAL_DESCRIPTION(1156, "Mô tả nhân sự thực tế không được vượt quá 1000 ký tự",
            HttpStatus.BAD_REQUEST),
    ABSENT_EMPLOYEE_HAS_WORKING_MINUTES(1157, "Nhân viên vắng mặt phải có số phút làm việc bằng 0",
            HttpStatus.BAD_REQUEST),
    EMPLOYEE_ACTUAL_REPORT_LOCKED(1158, "Không thể thay đổi nhân sự của báo cáo đã phê duyệt hoặc khóa",
            HttpStatus.BAD_REQUEST),
    EMPLOYEE_ACTUAL_STAGING_EXISTS(1159, "Nhân viên đã tồn tại trong báo cáo này", HttpStatus.BAD_REQUEST),
    EMPLOYEE_ACTUAL_STAGING_NOT_FOUND(1160, "Dữ liệu nhân sự thực tế tạm không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_REPORT_APPROVER_ID(1161, "Người duyệt báo cáo không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_PRODUCTION_REPORT_REMARK(1162, "Ghi chú duyệt không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    PRODUCTION_REPORT_ALREADY_CREATED(1163, "Báo cáo chính thức đã được tạo từ staging này", HttpStatus.BAD_REQUEST),
    PRODUCTION_REPORT_NOT_FOUND(1164, "Báo cáo sản xuất chính thức không tồn tại", HttpStatus.NOT_FOUND),
    SIZE_MACHINE_SERIAL_NUMBER(1165, "Số serial máy không được vượt quá 100 ký tự", HttpStatus.BAD_REQUEST),
    MACHINE_SERIAL_NUMBER_EXISTS(1166, "Số serial máy đã tồn tại", HttpStatus.BAD_REQUEST),
    INVALID_MACHINE_INSTALLATION_DATE(1167, "Ngày lắp đặt máy không được ở tương lai", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCTION_REPORT_DATE_RANGE(1168, "Ngày bắt đầu không được lớn hơn ngày kết thúc", HttpStatus.BAD_REQUEST),
    NOT_BLANK_REVIEW_COMMENT(1169, "Lý do yêu cầu chỉnh sửa không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_REVIEW_COMMENT(1170, "Lý do yêu cầu chỉnh sửa không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_DEPARTMENT_TYPE(1171, "Loại phòng ban không được để trống", HttpStatus.BAD_REQUEST),
    DEPARTMENT_TYPE_EXISTS(1172, "Loại phòng ban đã tồn tại trong nhà máy", HttpStatus.BAD_REQUEST),
    PRODUCTION_REPORT_ORGANIZATION_IMMUTABLE(1173,
            "Không được thay đổi cơ cấu nhà máy, phòng ban, dây chuyền hoặc tổ của báo cáo sau khi tạo",
            HttpStatus.BAD_REQUEST),
    STAGING_DETAIL_PARENT_IMMUTABLE(1174,
            "Không được chuyển dữ liệu chi tiết sang báo cáo sản xuất tạm khác", HttpStatus.BAD_REQUEST),
    STAGING_DETAIL_REQUIRES_DRAFT(1175,
            "Chỉ được thay đổi dữ liệu chi tiết khi báo cáo sản xuất tạm ở trạng thái nháp",
            HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED(1200, "Bạn cần đăng nhập để thực hiện thao tác này", HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(1201, "Bạn không có quyền thực hiện thao tác này", HttpStatus.FORBIDDEN),
    INVALID_CREDENTIALS(1202, "Tên đăng nhập hoặc mật khẩu không chính xác", HttpStatus.UNAUTHORIZED),
    USERNAME_EXISTS(1203, "Tên đăng nhập đã tồn tại", HttpStatus.BAD_REQUEST),
    EMPLOYEE_ACCOUNT_EXISTS(1204, "Nhân viên này đã có tài khoản", HttpStatus.BAD_REQUEST),
    USER_NOT_FOUND(1205, "Tài khoản không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_USER_EMPLOYEE_ID(1206, "Nhân viên của tài khoản không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_USERNAME(1207, "Tên đăng nhập không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_USERNAME(1208, "Tên đăng nhập phải từ 4 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_PASSWORD(1209, "Mật khẩu không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_PASSWORD(1210, "Mật khẩu phải từ 8 đến 100 ký tự", HttpStatus.BAD_REQUEST),
    NOT_EMPTY_USER_ROLES(1211, "Tài khoản phải có ít nhất một vai trò", HttpStatus.BAD_REQUEST),
    ROLE_NOT_FOUND(1212, "Vai trò không tồn tại", HttpStatus.NOT_FOUND),
    NOT_BLANK_TOKEN(1213, "Token không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_TOKEN(1214, "Token không hợp lệ hoặc đã hết hạn", HttpStatus.UNAUTHORIZED),
    INVALID_CURRENT_PASSWORD(1215, "Mật khẩu hiện tại không chính xác", HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_MUST_DIFFER(1216, "Mật khẩu mới phải khác mật khẩu hiện tại", HttpStatus.BAD_REQUEST),
    NOT_NULL_LEAVE_FROM_DATE(1217, "Ngày bắt đầu nghỉ không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_LEAVE_TO_DATE(1218, "Ngày kết thúc nghỉ không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_LEAVE_TYPE(1219, "Loại nghỉ phép không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_LEAVE_REASON(1220, "Lý do nghỉ phép không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_LEAVE_DATE_RANGE(1221, "Ngày kết thúc nghỉ phải từ ngày bắt đầu trở đi", HttpStatus.BAD_REQUEST),
    NOTIFICATION_NOT_FOUND(1222, "Thông báo không tồn tại hoặc không thuộc nhân viên hiện tại", HttpStatus.NOT_FOUND),
    DATA_SCOPE_NOT_FOUND(1223, "Phạm vi dữ liệu không tồn tại", HttpStatus.NOT_FOUND),
    FINANCIAL_CATEGORY_NOT_FOUND(1300, "Danh mục tài chính không tồn tại", HttpStatus.NOT_FOUND),
    FINANCIAL_CATEGORY_CODE_EXISTS(1301, "Mã danh mục tài chính đã tồn tại", HttpStatus.BAD_REQUEST),
    FINANCIAL_RECORD_NOT_FOUND(1302, "Bản ghi tài chính không tồn tại", HttpStatus.NOT_FOUND),
    INVALID_FINANCIAL_HIERARCHY(1303, "Nhà máy, phòng ban và dây chuyền không cùng một cơ cấu", HttpStatus.BAD_REQUEST),
    INVALID_FINANCIAL_CATEGORY_TYPE(1304, "Nhóm chi phí chỉ áp dụng cho danh mục chi phí", HttpStatus.BAD_REQUEST),
    WAREHOUSE_NOT_FOUND(1310, "Kho không tồn tại", HttpStatus.NOT_FOUND),
    WAREHOUSE_CODE_EXISTS(1311, "Mã kho đã tồn tại", HttpStatus.BAD_REQUEST),
    INVENTORY_TRANSACTION_NOT_FOUND(1312, "Giao dịch kho không tồn tại", HttpStatus.NOT_FOUND),
    INSUFFICIENT_INVENTORY(1313, "Số lượng tồn kho không đủ để xuất", HttpStatus.BAD_REQUEST),
    INVALID_PAID_AMOUNT(1314, "Số tiền đã thanh toán không được lớn hơn tổng tiền", HttpStatus.BAD_REQUEST),

    INVALID_INVENTORY_DATE_RANGE(1315, "Khoảng ngày giao dịch kho không hợp lệ", HttpStatus.BAD_REQUEST),
    INVENTORY_TRANSACTION_ALREADY_REVERSED(1316, "Giao dịch kho đã được đảo hoặc chính là giao dịch đảo", HttpStatus.CONFLICT),
    INVENTORY_REVERSAL_REASON_REQUIRED(1317, "Phải nhập lý do đảo giao dịch kho", HttpStatus.BAD_REQUEST),
    INVENTORY_UNIT_COST_REQUIRED(1318, "Đơn giá là bắt buộc đối với giao dịch nhập kho", HttpStatus.BAD_REQUEST),
    NOT_BLANK_INVENTORY_REVERSAL_REASON(1319, "Lý do đảo giao dịch kho không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_INVENTORY_REVERSAL_REASON(1320, "Lý do đảo giao dịch kho không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),

    FINANCIAL_RECORD_INACTIVE(1321, "Bản ghi tài chính đã ngừng hoạt động", HttpStatus.CONFLICT),
    FINANCIAL_RECORD_LOCKED(1322, "Chỉ bản ghi tài chính nháp mới được sửa hoặc xóa", HttpStatus.CONFLICT),
    FINANCIAL_RECORD_NOT_POSTED(1323, "Bản ghi tài chính chưa được ghi sổ", HttpStatus.CONFLICT),
    FINANCIAL_VOID_REASON_REQUIRED(1324, "Phải nhập lý do hủy ghi sổ", HttpStatus.BAD_REQUEST),
    FINANCIAL_RECORD_HAS_PAYMENTS(1325, "Phải đảo các thanh toán trước khi hủy ghi sổ", HttpStatus.CONFLICT),
    INVALID_FINANCIAL_DATE_RANGE(1326, "Khoảng ngày tài chính không hợp lệ", HttpStatus.BAD_REQUEST),
    FINANCIAL_PAYMENT_NOT_FOUND(1327, "Thanh toán tài chính không tồn tại", HttpStatus.NOT_FOUND),
    FINANCIAL_PAYMENT_ALREADY_REVERSED(1328, "Thanh toán đã được đảo hoặc chính là giao dịch đảo", HttpStatus.CONFLICT),
    FINANCIAL_PAYMENT_REVERSAL_REASON_REQUIRED(1329, "Phải nhập lý do đảo thanh toán", HttpStatus.BAD_REQUEST),
    NOT_BLANK_FINANCIAL_VOID_REASON(1330, "Lý do hủy ghi sổ không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_FINANCIAL_VOID_REASON(1331, "Lý do hủy ghi sổ không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_FINANCIAL_PAYMENT_DATE(1332, "Ngày thanh toán không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_FINANCIAL_PAYMENT_AMOUNT(1333, "Số tiền thanh toán không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_FINANCIAL_PAYMENT_AMOUNT(1334, "Số tiền thanh toán phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    SIZE_FINANCIAL_PAYMENT_REFERENCE(1335, "Mã tham chiếu thanh toán không được vượt quá 100 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_FINANCIAL_PAYMENT_NOTE(1336, "Ghi chú thanh toán không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_FINANCIAL_PAYMENT_REVERSAL_REASON(1337, "Lý do đảo thanh toán không được để trống", HttpStatus.BAD_REQUEST),

    WORK_SCHEDULE_EXISTS(1400, "Nhân viên đã có lịch làm trong ngày này", HttpStatus.CONFLICT),
    WORK_SCHEDULE_NOT_FOUND(1401, "Lịch làm việc không tồn tại", HttpStatus.NOT_FOUND),
    ATTENDANCE_TIME_REQUIRED(1402, "Phải nhập giờ vào và giờ ra khi nhân viên có làm việc", HttpStatus.BAD_REQUEST),
    ATTENDANCE_INVALID_TIME_RANGE(1403, "Giờ ra phải lớn hơn giờ vào và cùng ngày làm việc", HttpStatus.BAD_REQUEST),
    INVALID_LEAVE_DECISION(1404, "Quyết định nghỉ phép không hợp lệ", HttpStatus.BAD_REQUEST),
    LEAVE_REQUEST_NOT_FOUND(1405, "Đơn nghỉ phép không tồn tại", HttpStatus.NOT_FOUND),
    LEAVE_REQUEST_NOT_PENDING(1406, "Đơn nghỉ phép đã được xử lý", HttpStatus.CONFLICT),
    LEAVE_REQUEST_OVERLAP(1407, "Thời gian nghỉ bị trùng với một đơn nghỉ đang hiệu lực", HttpStatus.CONFLICT),
    EMPLOYEE_KPI_EXISTS(1408, "KPI của nhân viên trong kỳ này đã tồn tại", HttpStatus.CONFLICT),
    EMPLOYEE_KPI_NOT_FOUND(1409, "KPI nhân viên không tồn tại", HttpStatus.NOT_FOUND),
    INVALID_KPI_PERIOD(1410, "Ngày kết thúc kỳ KPI phải từ ngày bắt đầu trở đi", HttpStatus.BAD_REQUEST),
    INVALID_KPI_SCORE(1411, "Điểm KPI phải nằm trong khoảng từ 0 đến 100", HttpStatus.BAD_REQUEST),
    OVERTIME_REQUEST_EXISTS(1412, "Nhân viên đã có đăng ký tăng ca trong ngày này", HttpStatus.CONFLICT),
    INVALID_OVERTIME_DECISION(1413, "Quyết định tăng ca không hợp lệ", HttpStatus.BAD_REQUEST),
    OVERTIME_REQUEST_NOT_FOUND(1414, "Đăng ký tăng ca không tồn tại", HttpStatus.NOT_FOUND),
    OVERTIME_REQUEST_NOT_PENDING(1415, "Đăng ký tăng ca đã được xử lý", HttpStatus.CONFLICT),
    INVALID_ASSIGNMENT_TYPE(1416, "Kiểu điều chuyển nhân sự không hợp lệ", HttpStatus.BAD_REQUEST),
    INVALID_ASSIGNMENT_DATE_RANGE(1417, "Khoảng ngày điều chuyển nhân sự không hợp lệ", HttpStatus.BAD_REQUEST),
    EMPLOYEE_ASSIGNMENT_OVERLAP(1418, "Nhân viên đã có điều chuyển trùng thời gian", HttpStatus.CONFLICT),
    EMPLOYEE_ASSIGNMENT_NOT_FOUND(1419, "Điều chuyển nhân sự không tồn tại", HttpStatus.NOT_FOUND),
    NOT_NULL_SCHEDULE_EMPLOYEE_ID(1420, "Nhân viên của lịch làm không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_SCHEDULE_SHIFT_ID(1421, "Ca làm của lịch không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_SCHEDULE_WORK_DATE(1422, "Ngày làm việc không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_SCHEDULE_NOTE(1423, "Ghi chú lịch làm không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_ATTENDANCE_EMPLOYEE_ID(1424, "Nhân viên chấm công không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_ATTENDANCE_WORK_DATE(1425, "Ngày chấm công không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_ATTENDANCE_NOTE(1426, "Ghi chú chấm công không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_LEAVE_DECISION(1427, "Quyết định nghỉ phép không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_KPI_EMPLOYEE_ID(1428, "Nhân viên KPI không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_KPI_PERIOD_START(1429, "Ngày bắt đầu kỳ KPI không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_KPI_PERIOD_END(1430, "Ngày kết thúc kỳ KPI không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_KPI_NOTE(1431, "Ghi chú KPI không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_NOTIFICATION_RECIPIENT(1432, "Người nhận thông báo không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_NOTIFICATION_TITLE(1433, "Tiêu đề thông báo không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_NOTIFICATION_TITLE(1434, "Tiêu đề thông báo không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_NOTIFICATION_MESSAGE(1435, "Nội dung thông báo không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_NOTIFICATION_MESSAGE(1436, "Nội dung thông báo không được vượt quá 2000 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_NOTIFICATION_ACTION_URL(1437, "Liên kết thông báo không được vượt quá 500 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_OVERTIME_WORK_DATE(1438, "Ngày tăng ca không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_OVERTIME_MINUTES(1439, "Số phút tăng ca không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_OVERTIME_MINUTES(1440, "Số phút tăng ca phải từ 1 đến 720 phút", HttpStatus.BAD_REQUEST),
    NOT_BLANK_OVERTIME_REASON(1441, "Lý do tăng ca không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_OVERTIME_REASON(1442, "Lý do tăng ca không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_OVERTIME_DECISION(1443, "Quyết định tăng ca không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_ASSIGNMENT_EMPLOYEE_ID(1444, "Nhân viên điều chuyển không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_ASSIGNMENT_TARGET_TEAM_ID(1445, "Tổ đích không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_ASSIGNMENT_FROM_DATE(1446, "Ngày bắt đầu điều chuyển không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_ASSIGNMENT_REASON(1447, "Lý do điều chuyển không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_ASSIGNMENT_REASON(1448, "Lý do điều chuyển không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),

    MAINTENANCE_REQUEST_NOT_FOUND(1500, "Yêu cầu bảo trì không tồn tại", HttpStatus.NOT_FOUND),
    INVALID_MAINTENANCE_REQUEST_TRANSITION(1501, "Chuyển trạng thái yêu cầu bảo trì không hợp lệ", HttpStatus.CONFLICT),
    MAINTENANCE_RESOLUTION_REQUIRED(1502, "Phải nhập kết quả xử lý khi hoàn tất yêu cầu bảo trì", HttpStatus.BAD_REQUEST),
    MAINTENANCE_SCHEDULE_NOT_FOUND(1503, "Lịch bảo trì không tồn tại", HttpStatus.NOT_FOUND),
    INVALID_MAINTENANCE_DATE_RANGE(1504, "Khoảng thời gian bảo trì không hợp lệ", HttpStatus.BAD_REQUEST),
    MAINTENANCE_WORK_ORDER_NOT_FOUND(1505, "Phiếu công việc bảo trì không tồn tại", HttpStatus.NOT_FOUND),
    MAINTENANCE_WORK_ORDER_SOURCE_REQUIRED(1506, "Phiếu bảo trì phải gắn với yêu cầu hoặc lịch bảo trì", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_WORK_ORDER_TRANSITION(1507, "Chuyển trạng thái phiếu bảo trì không hợp lệ", HttpStatus.CONFLICT),
    INVALID_MAINTENANCE_ACTUAL_TIME_RANGE(1508, "Thời gian thực tế bảo trì không hợp lệ", HttpStatus.BAD_REQUEST),
    MAINTENANCE_COMPLETION_NOTE_REQUIRED(1509, "Phải nhập kết quả hoàn thành bảo trì", HttpStatus.BAD_REQUEST),
    MAINTENANCE_PART_EXISTS(1510, "Vật tư đã tồn tại trong phiếu bảo trì", HttpStatus.CONFLICT),
    MAINTENANCE_PART_NOT_FOUND(1511, "Vật tư sử dụng trong phiếu bảo trì không tồn tại", HttpStatus.NOT_FOUND),
    MAINTENANCE_DOWNTIME_MACHINE_MISMATCH(1512, "Dữ liệu dừng máy không thuộc máy của yêu cầu bảo trì", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_WORK_ORDER_SOURCE(1513, "Nguồn phiếu bảo trì không hợp lệ hoặc không cùng máy", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_SCHEDULE_DATE(1514, "Ngày đến hạn phải từ ngày hoàn thành gần nhất trở đi", HttpStatus.BAD_REQUEST),
    MAINTENANCE_WORK_ORDER_LOCKED(1515, "Phiếu bảo trì đã hoàn tất hoặc đã hủy nên không thể thay đổi", HttpStatus.CONFLICT),
    NOT_NULL_MAINTENANCE_MACHINE_ID(1516, "Máy bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_PRIORITY(1517, "Mức ưu tiên bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MAINTENANCE_TITLE(1518, "Tiêu đề bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MAINTENANCE_TITLE(1519, "Tiêu đề bảo trì không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MAINTENANCE_DESCRIPTION(1520, "Mô tả bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MAINTENANCE_DESCRIPTION(1521, "Mô tả bảo trì không được vượt quá 2000 ký tự", HttpStatus.BAD_REQUEST),
    SIZE_MAINTENANCE_IMPACT(1522, "Mô tả ảnh hưởng không được vượt quá 1000 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_REQUEST_STATUS(1523, "Trạng thái yêu cầu bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MAINTENANCE_RESOLUTION_NOTE(1524, "Kết quả xử lý không được vượt quá 2000 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_TYPE(1525, "Loại bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    NOT_BLANK_MAINTENANCE_SCHEDULE_NAME(1526, "Tên lịch bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MAINTENANCE_SCHEDULE_NAME(1527, "Tên lịch bảo trì không được vượt quá 255 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_INTERVAL(1528, "Chu kỳ bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_INTERVAL(1529, "Chu kỳ bảo trì phải từ 1 đến 3650 ngày", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_NEXT_DUE_DATE(1530, "Ngày bảo trì tiếp theo không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_PLANNED_START(1531, "Thời gian dự kiến bắt đầu không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_PLANNED_END(1532, "Thời gian dự kiến kết thúc không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_COST(1533, "Chi phí bảo trì không được âm", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_WORK_ORDER_STATUS(1534, "Trạng thái phiếu bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_MAINTENANCE_COMPLETION_NOTE(1535, "Kết quả hoàn thành không được vượt quá 2000 ký tự", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_MATERIAL_ID(1536, "Vật tư bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_PART_QUANTITY(1537, "Số lượng vật tư bảo trì không được để trống", HttpStatus.BAD_REQUEST),
    INVALID_MAINTENANCE_PART_QUANTITY(1538, "Số lượng vật tư bảo trì phải lớn hơn 0", HttpStatus.BAD_REQUEST),
    NOT_NULL_MAINTENANCE_PART_UNIT_COST(1539, "Đơn giá vật tư bảo trì không được để trống", HttpStatus.BAD_REQUEST),

    PRODUCT_CODE_EXISTS(1600, "Mã sản phẩm đã tồn tại", HttpStatus.CONFLICT),
    PRODUCT_NOT_FOUND(1601, "Sản phẩm không tồn tại", HttpStatus.NOT_FOUND),
    PRODUCTION_PLAN_INVALID_PERIOD(1602, "Khoảng thời gian kế hoạch sản xuất không hợp lệ", HttpStatus.BAD_REQUEST),
    PRODUCTION_PLAN_NOT_FOUND(1603, "Kế hoạch sản xuất không tồn tại", HttpStatus.NOT_FOUND),
    PRODUCTION_PLAN_INVALID_HIERARCHY(1604, "Nhà máy và dây chuyền của kế hoạch không cùng cơ cấu", HttpStatus.BAD_REQUEST),
    PRODUCTION_PLAN_INACTIVE_MASTER_DATA(1605, "Dữ liệu danh mục của kế hoạch đã ngừng hoạt động", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_NOT_DRAFT(1606, "Chỉ kế hoạch nháp mới được thực hiện thao tác này", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_EXISTS(1607, "Kế hoạch sản xuất trùng phạm vi, sản phẩm và thời gian", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_STRUCTURE_LOCKED(1608, "Không thể thay đổi cơ cấu của kế hoạch đã có lệnh sản xuất", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_QUANTITY_BELOW_ALLOCATED(1609, "Sản lượng kế hoạch không được nhỏ hơn tổng đã phân bổ", HttpStatus.BAD_REQUEST),
    INVALID_PRODUCTION_PLAN_TRANSITION(1610, "Chuyển trạng thái kế hoạch sản xuất không hợp lệ", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_HAS_NO_ORDERS(1611, "Kế hoạch chưa có lệnh sản xuất", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_HAS_OPEN_ORDERS(1612, "Kế hoạch còn lệnh sản xuất chưa hoàn tất", HttpStatus.CONFLICT),
    PRODUCTION_PLAN_HAS_ORDERS(1613, "Không thể xóa kế hoạch đã có lệnh sản xuất", HttpStatus.CONFLICT),
    PRODUCTION_ORDER_INVALID_PERIOD(1614, "Khoảng thời gian lệnh sản xuất không hợp lệ", HttpStatus.BAD_REQUEST),
    PRODUCTION_ORDER_NOT_FOUND(1615, "Lệnh sản xuất không tồn tại", HttpStatus.NOT_FOUND),
    PRODUCTION_PLAN_NOT_APPROVED(1616, "Kế hoạch sản xuất chưa được duyệt", HttpStatus.CONFLICT),
    PRODUCTION_ORDER_INVALID_HIERARCHY(1617, "Tổ, máy hoặc ca không thuộc phạm vi của kế hoạch", HttpStatus.BAD_REQUEST),
    PRODUCTION_ORDER_INACTIVE_MASTER_DATA(1618, "Dữ liệu danh mục của lệnh sản xuất đã ngừng hoạt động", HttpStatus.CONFLICT),
    PRODUCTION_ORDER_TOTAL_EXCEEDS_PLAN(1619, "Tổng sản lượng lệnh sản xuất vượt sản lượng kế hoạch", HttpStatus.BAD_REQUEST),
    PRODUCTION_ORDER_NOT_DRAFT(1620, "Chỉ lệnh sản xuất nháp mới được sửa cấu trúc", HttpStatus.CONFLICT),
    INVALID_PRODUCTION_ORDER_TRANSITION(1621, "Chuyển trạng thái lệnh sản xuất không hợp lệ", HttpStatus.CONFLICT),

    STAGING_EXCEL_EMPTY_FILE(1700, "Vui lòng chọn file Excel cần nhập", HttpStatus.BAD_REQUEST),
    STAGING_EXCEL_FILE_TOO_LARGE(1701, "File Excel vượt quá giới hạn 10 MB", HttpStatus.PAYLOAD_TOO_LARGE),
    STAGING_EXCEL_INVALID_FORMAT(1702, "File không đúng định dạng Excel hoặc đã bị hỏng", HttpStatus.BAD_REQUEST),
    STAGING_REPORT_DELETE_REQUIRES_DRAFT(1703, "Chỉ được xóa báo cáo đang ở trạng thái DRAFT", HttpStatus.CONFLICT),

    AI_NOT_CONFIGURED(1800, "Chatbot AI chưa được cấu hình hoặc chưa được bật", HttpStatus.SERVICE_UNAVAILABLE),
    AI_PROVIDER_UNAVAILABLE(1801, "Không thể kết nối dịch vụ AI. Vui lòng thử lại sau", HttpStatus.SERVICE_UNAVAILABLE),
    AI_PROVIDER_INVALID_RESPONSE(1802, "Dịch vụ AI trả về dữ liệu không hợp lệ", HttpStatus.BAD_GATEWAY),
    AI_TOOL_NOT_ALLOWED(1803, "Công cụ AI không tồn tại hoặc vai trò hiện tại không được sử dụng", HttpStatus.FORBIDDEN),
    AI_TOOL_ARGUMENT_INVALID(1804, "Điều kiện truy vấn do AI tạo không hợp lệ", HttpStatus.BAD_REQUEST),
    AI_DATE_RANGE_TOO_LARGE(1805, "Khoảng thời gian chatbot truy vấn vượt quá giới hạn cho phép", HttpStatus.BAD_REQUEST),
    AI_TOO_MANY_TOOL_CALLS(1806, "Chatbot yêu cầu quá nhiều công cụ trong một lượt", HttpStatus.BAD_REQUEST),
    AI_WORKSPACE_ROLE_INVALID(1807, "Vai trò màn hình không hợp lệ hoặc chưa được cấp cho tài khoản", HttpStatus.FORBIDDEN),
    NOT_BLANK_AI_MESSAGE(1808, "Câu hỏi chatbot không được để trống", HttpStatus.BAD_REQUEST),
    SIZE_AI_MESSAGE(1809, "Câu hỏi chatbot không được vượt quá 2000 ký tự", HttpStatus.BAD_REQUEST),
    AI_RATE_LIMIT_EXCEEDED(1810, "Bạn đã gửi quá nhiều câu hỏi. Vui lòng chờ một phút rồi thử lại", HttpStatus.TOO_MANY_REQUESTS),
    ;

    ErrorCode(int code, String message, HttpStatusCode statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }

    private int code;
    private String message;
    private HttpStatusCode statusCode;
}
