import { useEffect, useMemo, useState } from 'react'
import { adminApi, type DataScopeType, type DepartmentTypeOption, type UserDataScope } from '../api/adminApi'
import { DataTable, Panel, StatusBadge } from '../components/ui'

type Field={key:string;label:string;type?:string;required?:boolean;source?:string}
type MasterConfig={label:string;fields:Field[];columns?:Field[]}
const configs:Record<string,MasterConfig>={
 factories:{label:'Nhà máy',fields:[{key:'code',label:'Mã nhà máy',required:true},{key:'name',label:'Tên nhà máy',required:true},{key:'address',label:'Địa chỉ',required:true}]},
 departments:{
  label:'Phòng ban',
  fields:[
   {key:'factoryId',label:'Nhà máy',required:true,source:'factories'},
   {key:'departmentType',label:'Loại phòng ban',type:'department-type',required:true},
   {key:'description',label:'Mô tả',type:'textarea'}
  ],
  columns:[
   {key:'factoryId',label:'Nhà máy',source:'factories'},
   {key:'code',label:'Mã phòng ban'},
   {key:'name',label:'Tên phòng ban'},
   {key:'departmentType',label:'Loại phòng ban'},
   {key:'description',label:'Mô tả'}
  ]
 },
 'production-lines':{label:'Dây chuyền',fields:[{key:'departmentId',label:'Phòng ban',required:true,source:'departments'},{key:'code',label:'Mã dây chuyền',required:true},{key:'name',label:'Tên dây chuyền',required:true},{key:'description',label:'Mô tả'}]},
 teams:{label:'Tổ sản xuất',fields:[{key:'productionLineId',label:'Dây chuyền',required:true,source:'production-lines'},{key:'code',label:'Mã tổ',required:true},{key:'name',label:'Tên tổ',required:true},{key:'description',label:'Mô tả'}]},
 'machine-types':{label:'Loại máy',fields:[{key:'code',label:'Mã loại máy',required:true},{key:'name',label:'Tên loại máy',required:true},{key:'description',label:'Mô tả'}]},
 machines:{label:'Máy',fields:[{key:'code',label:'Mã máy',required:true},{key:'name',label:'Tên máy',required:true},{key:'serialNumber',label:'Số serial'},{key:'machineTypeId',label:'Loại máy',required:true,source:'machine-types'},{key:'teamId',label:'Tổ sản xuất',required:true,source:'teams'},{key:'installationDate',label:'Ngày lắp đặt',type:'date'},{key:'status',label:'Trạng thái',type:'machine-status'},{key:'description',label:'Mô tả'}]},
 employees:{label:'Nhân viên',fields:[{key:'teamId',label:'Tổ sản xuất',source:'teams'},{key:'code',label:'Mã nhân viên',required:true},{key:'fullName',label:'Họ và tên',required:true},{key:'position',label:'Chức vụ',required:true},{key:'hireDate',label:'Ngày vào làm',type:'date',required:true}]},
 shifts:{label:'Ca làm việc',fields:[{key:'code',label:'Mã ca',required:true},{key:'name',label:'Tên ca',required:true},{key:'startTime',label:'Giờ bắt đầu',type:'time',required:true},{key:'endTime',label:'Giờ kết thúc',type:'time',required:true}]},
 'downtime-reasons':{label:'Lý do dừng máy',fields:[{key:'code',label:'Mã lý do',required:true},{key:'name',label:'Tên lý do',required:true},{key:'reasonType',label:'Loại dừng',type:'reason-type',required:true},{key:'description',label:'Mô tả'}]},
 'quality-error-types':{label:'Loại lỗi chất lượng',fields:[{key:'code',label:'Mã lỗi',required:true},{key:'name',label:'Tên lỗi',required:true},{key:'severity',label:'Mức độ',type:'severity',required:true},{key:'description',label:'Mô tả'}]},
 materials:{label:'Vật tư',fields:[{key:'code',label:'Mã vật tư',required:true},{key:'name',label:'Tên vật tư',required:true},{key:'unit',label:'Đơn vị tính',required:true},{key:'description',label:'Mô tả'}]},
 users:{label:'Tài khoản & phân quyền',fields:[{key:'employeeId',label:'Nhân viên',source:'employees',required:true},{key:'username',label:'Tên đăng nhập',required:true},{key:'password',label:'Mật khẩu ban đầu',type:'password',required:true},{key:'roles',label:'Vai trò',type:'roles',required:true}]}}

const scopeDefinitions:Record<DataScopeType,{label:string;path:string}>={
 FACTORY:{label:'Nhà máy',path:'factories'},
 DEPARTMENT:{label:'Phòng ban',path:'departments'},
 PRODUCTION_LINE:{label:'Dây chuyền',path:'production-lines'},
 TEAM:{label:'Tổ sản xuất',path:'teams'}
}

export default function AdminMasterPage({section}:{section?:string}){
 const[path,setPath]=useState(section??'factories'),[rows,setRows]=useState<any[]>([]),[options,setOptions]=useState<Record<string,any[]>>({}),[form,setForm]=useState<Record<string,string>>({})
 const[departmentTypes,setDepartmentTypes]=useState<DepartmentTypeOption[]>([])
 const[leaderTeam,setLeaderTeam]=useState<any|null>(null),[leaderCandidates,setLeaderCandidates]=useState<any[]>([]),[leaderEmployeeId,setLeaderEmployeeId]=useState(''),[leaderError,setLeaderError]=useState(''),[leaderBusy,setLeaderBusy]=useState(false)
 const[scopeUser,setScopeUser]=useState<any|null>(null),[userScopes,setUserScopes]=useState<UserDataScope[]>([]),[scopeType,setScopeType]=useState<DataScopeType>('FACTORY'),[scopeTargetId,setScopeTargetId]=useState(''),[scopeTargets,setScopeTargets]=useState<any[]>([]),[scopeError,setScopeError]=useState(''),[scopeBusy,setScopeBusy]=useState(false)
 const[message,setMessage]=useState<{text:string;error:boolean}|null>(null),[busy,setBusy]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[modalOpen,setModalOpen]=useState(false),[resetUser,setResetUser]=useState<any|null>(null),[resetValue,setResetValue]=useState(''),config=configs[path]
 const sources=useMemo(()=>[...new Set(config.fields.flatMap(f=>f.source?[f.source]:[]))],[config])
 useEffect(()=>{if(section&&configs[section])setPath(section)},[section])
 async function load(){try{setRows(await adminApi.list(path))}catch(e){setMessage({text:(e as Error).message,error:true})}}
 useEffect(()=>{
  setForm({});setEditingId(null);setModalOpen(false);setLeaderTeam(null);setScopeUser(null);setMessage(null);void load()
  const optionRequest=Promise.all(sources.map(async s=>[s,await adminApi.list(s)]as const))
  const departmentTypeRequest=path==='departments'?adminApi.departmentTypes():Promise.resolve([])
  Promise.all([optionRequest,departmentTypeRequest]).then(([optionEntries,typeEntries])=>{
   setOptions(Object.fromEntries(optionEntries));setDepartmentTypes(typeEntries)
  }).catch(e=>setMessage({text:(e as Error).message,error:true}))
 },[path])
 function openCreate(){setForm({});setEditingId(null);setMessage(null);setModalOpen(true)}
 function edit(row:any){const next:Record<string,string>={};config.fields.forEach(f=>{let value=row[f.key];if(value==null&&f.key.endsWith('Id'))value=row[f.key.slice(0,-2)]?.id;if(Array.isArray(value))value=value.join(',');if(value!=null)next[f.key]=String(value)});setForm(next);setEditingId(row.id);setMessage(null);setModalOpen(true)}
 function closeModal(){if(busy)return;setModalOpen(false);setEditingId(null);setForm({});setMessage(null)}
 async function save(){const missing=!editingId&&config.fields.find(f=>f.required&&!form[f.key]?.trim());if(missing){setMessage({text:`Vui lòng nhập/chọn ${missing.label}.`,error:true});return}if(path==='users'&&!editingId&&form.password.length<8){setMessage({text:'Mật khẩu phải có ít nhất 8 ký tự.',error:true});return}const data=Object.fromEntries(Object.entries(form).filter(([,v])=>v!=='').map(([k,v])=>k.endsWith('Id')?[k,Number(v)]:[k,v.trim()]));setBusy(true);try{if(path==='users'){const selectedRoles=(form.roles??'').split(',').filter(Boolean);if(editingId)await adminApi.updateRoles(editingId,selectedRoles);else{const account=await adminApi.register({employeeId:Number(form.employeeId),username:form.username,password:form.password});await adminApi.updateRoles(account.userId,selectedRoles)}}else if(editingId)await adminApi.update(path,editingId,data);else await adminApi.create(path,{...data,active:true,...(path==='machines'&&!data.status?{status:'IDLE'}:{})});setModalOpen(false);setForm({});setEditingId(null);setMessage({text:`Đã lưu ${config.label} thành công.`,error:false});await load()}catch(e){setMessage({text:(e as Error).message,error:true})}finally{setBusy(false)}}
 async function remove(id:number){if(!confirm(`Bạn có chắc muốn xóa mềm ${config.label} #${id}?`))return;setBusy(true);try{await adminApi.remove(path,id);setMessage({text:`Đã xóa ${config.label} thành công.`,error:false});await load()}catch(e){setMessage({text:(e as Error).message,error:true})}finally{setBusy(false)}}
 async function resetPassword(){if(resetValue.length<8){setMessage({text:'Mật khẩu mới phải có ít nhất 8 ký tự.',error:true});return}setBusy(true);try{await adminApi.resetPassword(resetUser.id,resetValue);const username=resetUser.username;setResetUser(null);setResetValue('');setMessage({text:`Đã đặt lại mật khẩu cho ${username}. Các phiên đăng nhập cũ đã bị vô hiệu hóa.`,error:false})}catch(e){setMessage({text:(e as Error).message,error:true})}finally{setBusy(false)}}
 async function openLeaderModal(team:any){setLeaderTeam(team);setLeaderCandidates([]);setLeaderEmployeeId(team.leaderEmployeeId?String(team.leaderEmployeeId):'');setLeaderError('');setLeaderBusy(true);try{setLeaderCandidates(await adminApi.employeesByTeam(team.id))}catch(e){setLeaderError((e as Error).message)}finally{setLeaderBusy(false)}}
 function closeLeaderModal(){if(!leaderBusy){setLeaderTeam(null);setLeaderCandidates([]);setLeaderEmployeeId('');setLeaderError('')}}
 async function assignLeader(){if(!leaderTeam||!leaderEmployeeId){setLeaderError('Vui lòng chọn một nhân viên thuộc tổ.');return}setLeaderBusy(true);setLeaderError('');try{await adminApi.assignTeamLeader(leaderTeam.id,Number(leaderEmployeeId));const teamName=leaderTeam.name;setLeaderTeam(null);setMessage({text:`Đã gán tổ trưởng cho ${teamName}.`,error:false});await load()}catch(e){setLeaderError((e as Error).message)}finally{setLeaderBusy(false)}}
 async function removeLeader(){if(!leaderTeam)return;setLeaderBusy(true);setLeaderError('');try{await adminApi.removeTeamLeader(leaderTeam.id);const teamName=leaderTeam.name;setLeaderTeam(null);setMessage({text:`Đã gỡ tổ trưởng của ${teamName}.`,error:false});await load()}catch(e){setLeaderError((e as Error).message)}finally{setLeaderBusy(false)}}
 async function openScopeModal(user:any){setScopeUser(user);setUserScopes([]);setScopeType('FACTORY');setScopeTargetId('');setScopeTargets([]);setScopeError('');setScopeBusy(true);try{const[scopes,targets]=await Promise.all([adminApi.dataScopes(user.id),adminApi.list(scopeDefinitions.FACTORY.path)]);setUserScopes(scopes);setScopeTargets(targets)}catch(e){setScopeError((e as Error).message)}finally{setScopeBusy(false)}}
 function closeScopeModal(){if(!scopeBusy){setScopeUser(null);setUserScopes([]);setScopeTargets([]);setScopeTargetId('');setScopeError('')}}
 async function changeScopeType(next:DataScopeType){setScopeType(next);setScopeTargetId('');setScopeError('');setScopeBusy(true);try{setScopeTargets(await adminApi.list(scopeDefinitions[next].path))}catch(e){setScopeTargets([]);setScopeError((e as Error).message)}finally{setScopeBusy(false)}}
 async function addScope(){if(!scopeUser||!scopeTargetId){setScopeError(`Vui lòng chọn ${scopeDefinitions[scopeType].label.toLowerCase()}.`);return}setScopeBusy(true);setScopeError('');try{await adminApi.addDataScope(scopeUser.id,scopeType,Number(scopeTargetId));setUserScopes(await adminApi.dataScopes(scopeUser.id));setScopeTargetId('')}catch(e){setScopeError((e as Error).message)}finally{setScopeBusy(false)}}
 async function removeScope(dataScopeId:number){if(!scopeUser||!confirm('Bạn có chắc muốn thu hồi phạm vi dữ liệu này?'))return;setScopeBusy(true);setScopeError('');try{await adminApi.removeDataScope(scopeUser.id,dataScopeId);setUserScopes(await adminApi.dataScopes(scopeUser.id))}catch(e){setScopeError((e as Error).message)}finally{setScopeBusy(false)}}
 const roles=['ADMIN','DIRECTOR','FACTORY_MANAGER','DEPARTMENT_MANAGER','FINANCE','PRODUCTION_MANAGER','TEAM_LEADER','EMPLOYEE']
 const enumValues:Record<string,string[]>={'machine-status':['IDLE','RUNNING','STOPPED','MAINTENANCE','BREAKDOWN'],'reason-type':['PLANNED','UNPLANNED'],severity:['LOW','MEDIUM','HIGH','CRITICAL']}
 const selectedFactory=(options.factories??[]).find(x=>String(x.id)===form.factoryId)
 const selectedDepartmentType=departmentTypes.find(x=>x.type===form.departmentType)
 const visibleFields=config.fields.filter(f=>!(path==='users'&&editingId&&(f.key==='employeeId'||f.key==='password')))
 const fields=<><div className="form-grid">{visibleFields.map(f=>f.type==='roles'?<div className="field role-field" key={f.key}><span>Vai trò *</span><div className="role-options">{roles.map(role=>{const checked=(form.roles??'').split(',').includes(role);return <label key={role}><input type="checkbox" checked={checked} onChange={()=>{const current=(form.roles??'').split(',').filter(Boolean);setForm({...form,roles:(checked?current.filter(x=>x!==role):[...current,role]).join(',')})}}/>{role}</label>})}</div></div>:<label className="field" key={f.key}><span>{f.label}{f.required&&!editingId?' *':''}</span>{f.source?<select disabled={path==='users'&&!!editingId} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">-- Chọn {f.label.toLowerCase()} --</option>{(options[f.source]??[]).map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} - `:''}{x.name??x.fullName}</option>)}</select>:f.type==='department-type'?<select value={form[f.key]??''} onChange={e=>{const selected=departmentTypes.find(x=>x.type===e.target.value);setForm({...form,[f.key]:e.target.value,...(selected?{description:selected.description}:{description:''})})}}><option value="">-- Chọn loại phòng ban --</option>{departmentTypes.map(option=><option key={option.type} value={option.type}>{option.name} ({option.codeSuffix})</option>)}</select>:f.type&&enumValues[f.type]?<select value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">-- Chọn {f.label.toLowerCase()} --</option>{enumValues[f.type].map(v=><option key={v}>{v}</option>)}</select>:f.type==='textarea'?<textarea value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:<input disabled={path==='users'&&!!editingId} type={f.type??'text'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div>{path==='departments'&&selectedDepartmentType&&<p className="hint">Tên cố định: <strong>{selectedDepartmentType.name}</strong>. Mã tự sinh: <strong>{selectedFactory?`${selectedFactory.code}-${selectedDepartmentType.codeSuffix}`:`{MÃ_NHÀ_MÁY}-${selectedDepartmentType.codeSuffix}`}</strong>. Bạn có thể chỉnh lại phần mô tả trước khi lưu.</p>}</>
 const normalColumns=(config.columns??config.fields).map(f=>({key:f.key,label:f.label,render:(r:any)=>{if(f.source){const base=f.key.slice(0,-2);return r[`${base}Name`]??r[`${base}Code`]??r[f.key]??'—'}return Array.isArray(r[f.key])?r[f.key].join(', '):String(r[f.key]??'—')}}))
 const teamLeaderColumns=path==='teams'?[{key:'leaderEmployeeName',label:'Tổ trưởng',render:(r:any)=>r.leaderEmployeeId?`${r.leaderEmployeeCode} - ${r.leaderEmployeeName}`:'Chưa gán'}]:[]
 const userColumns=[{key:'employeeCode',label:'Mã nhân viên'},{key:'employeeName',label:'Nhân viên'},{key:'username',label:'Tên đăng nhập'},{key:'roles',label:'Vai trò',render:(r:any)=>r.roles?.join(', ')??'—'},{key:'enabled',label:'Sử dụng',render:(r:any)=><StatusBadge value={r.enabled}/>},{key:'accountNonLocked',label:'Khóa',render:(r:any)=><StatusBadge value={r.accountNonLocked?'Không khóa':'Đã khóa'}/>}]
 const tableColumns=[{key:'id',label:'ID'},...(path==='users'?userColumns:[...normalColumns,...teamLeaderColumns]),...(path==='users'?[]:[{key:'active',label:'Trạng thái',render:(r:any)=><StatusBadge value={r.active}/>}]),{key:'action',label:'Thao tác',render:(r:any)=><div className="admin-actions"><button disabled={busy} onClick={()=>edit(r)}>{path==='users'?'Phân quyền':'Sửa'}</button>{path==='teams'&&<button disabled={busy} onClick={()=>void openLeaderModal(r)}>{r.leaderEmployeeId?'Đổi tổ trưởng':'Gán tổ trưởng'}</button>}{path==='users'&&<button disabled={busy} onClick={()=>{setMessage(null);setResetValue('');setResetUser(r)}}>Đặt lại mật khẩu</button>}{path==='users'&&<button disabled={busy} onClick={()=>void openScopeModal(r)}>Phạm vi dữ liệu</button>}{path!=='users'&&<button disabled={busy} className="danger-link" onClick={()=>remove(r.id)}>Xóa</button>}{resetUser?.id===r.id&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setResetUser(null)}}><div className="modal reset-password-modal"><div className="admin-modal-header"><div><h2>Đặt lại mật khẩu</h2><p>{r.employeeName} — {r.username}</p></div><button className="modal-close" disabled={busy} onClick={()=>setResetUser(null)}>×</button></div><div className="reset-password-body"><label className="field"><span>Mật khẩu mới *</span><input autoFocus type="password" value={resetValue} onChange={e=>setResetValue(e.target.value)} placeholder="Tối thiểu 8 ký tự"/></label>{message&&<p className={`form-message${message.error?' error':''}`}>{message.text}</p>}</div><div className="form-actions"><button disabled={busy} onClick={()=>setResetUser(null)}>Hủy</button><button className="primary" disabled={busy} onClick={resetPassword}>{busy?'Đang xử lý...':'Xác nhận đặt lại'}</button></div></div></div>}</div>}]
 const leaderModal=leaderTeam&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeLeaderModal()}}><div className="modal admin-modal"><div className="admin-modal-header"><div><h2>{leaderTeam.leaderEmployeeId?'Đổi tổ trưởng':'Gán tổ trưởng'}</h2><p>{leaderTeam.code} — {leaderTeam.name}</p></div><button aria-label="Đóng" className="modal-close" disabled={leaderBusy} onClick={closeLeaderModal}>×</button></div><div className="form-grid"><label className="field"><span>Nhân viên thuộc tổ *</span><select autoFocus disabled={leaderBusy} value={leaderEmployeeId} onChange={e=>setLeaderEmployeeId(e.target.value)}><option value="">{leaderBusy?'Đang tải nhân viên...':'-- Chọn nhân viên --'}</option>{leaderCandidates.map(employee=><option key={employee.id} value={employee.id}>{employee.code} - {employee.fullName}{employee.position?` (${employee.position})`:''}</option>)}</select></label></div>{!leaderBusy&&leaderCandidates.length===0&&<p className="hint">Tổ này chưa có nhân viên hoạt động. Hãy phân nhân viên vào tổ trước khi gán tổ trưởng.</p>}<p className="hint">Danh sách chỉ hiển thị nhân viên đang hoạt động và thuộc đúng tổ này.</p>{leaderError&&<p className="form-message error">{leaderError}</p>}<div className="form-actions">{leaderTeam.leaderEmployeeId&&<button className="danger" disabled={leaderBusy} onClick={()=>void removeLeader()}>Gỡ tổ trưởng</button>}<button disabled={leaderBusy} onClick={closeLeaderModal}>Hủy</button><button className="primary" disabled={leaderBusy||!leaderEmployeeId} onClick={()=>void assignLeader()}>{leaderBusy?'Đang xử lý...':'Xác nhận gán'}</button></div></div></div>
 const scopeModal=scopeUser&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeScopeModal()}}><div className="modal admin-modal"><div className="admin-modal-header"><div><h2>Phạm vi dữ liệu</h2><p>{scopeUser.employeeName} — {scopeUser.username}</p></div><button aria-label="Đóng" className="modal-close" disabled={scopeBusy} onClick={closeScopeModal}>×</button></div>{scopeUser.roles?.some((role:string)=>role==='ADMIN'||role==='DIRECTOR')&&<p className="hint">ADMIN và DIRECTOR được xem toàn hệ thống nên không bắt buộc cấp phạm vi.</p>}<div className="form-grid"><label className="field"><span>Cấp phạm vi *</span><select disabled={scopeBusy} value={scopeType} onChange={e=>void changeScopeType(e.target.value as DataScopeType)}>{(Object.keys(scopeDefinitions) as DataScopeType[]).map(type=><option key={type} value={type}>{scopeDefinitions[type].label}</option>)}</select></label><label className="field"><span>{scopeDefinitions[scopeType].label} *</span><select disabled={scopeBusy} value={scopeTargetId} onChange={e=>setScopeTargetId(e.target.value)}><option value="">{scopeBusy?'Đang tải dữ liệu...':`-- Chọn ${scopeDefinitions[scopeType].label.toLowerCase()} --`}</option>{scopeTargets.map(target=><option key={target.id} value={target.id}>{target.code?`${target.code} - `:''}{target.name}</option>)}</select></label></div><div className="form-actions"><button className="primary" disabled={scopeBusy||!scopeTargetId} onClick={()=>void addScope()}>{scopeBusy?'Đang xử lý...':'Thêm phạm vi'}</button></div><p className="hint"><strong>Phạm vi đã cấp</strong> — một tài khoản có thể được cấp nhiều khu vực.</p><DataTable rows={userScopes} columns={[{key:'scopeType',label:'Cấp',render:(scope:any)=>scopeDefinitions[scope.scopeType as DataScopeType].label},{key:'scopeCode',label:'Mã'},{key:'scopeName',label:'Tên phạm vi'},{key:'action',label:'Thao tác',render:(scope:any)=><button className="danger-link" disabled={scopeBusy} onClick={()=>void removeScope(scope.id)}>Thu hồi</button>} ]}/>{scopeError&&<p className="form-message error">{scopeError}</p>}<div className="form-actions"><button disabled={scopeBusy} onClick={closeScopeModal}>Đóng</button></div></div></div>
 return <><div className="page-title"><div><h2>Quản trị dữ liệu nhà máy</h2><p>Quản lý đầy đủ danh mục tổ chức, nhân sự, ca làm, máy móc, chất lượng và vật tư</p></div><button className="admin-add-button" onClick={openCreate}>+ Thêm {config.label}</button></div><div className="step-tabs">{Object.entries(configs).map(([k,v])=><button key={k} className={path===k?'active':''} onClick={()=>setPath(k)}>{v.label}</button>)}</div>{message&&!modalOpen&&<p className={`form-message${message.error?' error':''}`}>{message.text}</p>}<Panel title={`Danh sách ${config.label}`}><DataTable rows={rows} columns={tableColumns}/></Panel>{modalOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeModal()}}><div className="modal admin-modal"><div className="admin-modal-header"><div><h2>{editingId?'Sửa':'Thêm'} {config.label}</h2><p>{editingId?`Cập nhật bản ghi #${editingId}`:'Nhập đầy đủ thông tin bản ghi mới'}</p></div><button aria-label="Đóng" className="modal-close" onClick={closeModal}>×</button></div>{fields}{message&&<p className={`form-message${message.error?' error':''}`}>{message.text}</p>}<div className="form-actions"><button disabled={busy} onClick={closeModal}>Hủy</button><button className="primary" disabled={busy} onClick={save}>{busy?'Đang xử lý...':editingId?'Lưu thay đổi':'Thêm mới'}</button></div></div></div>}{leaderModal}{scopeModal}</>
}
