import { useEffect, useMemo, useState } from 'react'
import { adminApi } from '../api/adminApi'
import { DataTable, Panel, StatusBadge } from '../components/ui'

type Field={key:string;label:string;type?:string;required?:boolean;source?:string}
const configs:Record<string,{label:string;fields:Field[]}>={
 factories:{label:'Nhà máy',fields:[{key:'code',label:'Mã nhà máy',required:true},{key:'name',label:'Tên nhà máy',required:true},{key:'address',label:'Địa chỉ',required:true}]},
 departments:{label:'Phòng ban',fields:[{key:'factoryId',label:'Nhà máy',required:true,source:'factories'},{key:'code',label:'Mã phòng ban',required:true},{key:'name',label:'Tên phòng ban',required:true},{key:'description',label:'Mô tả'}]},
 'production-lines':{label:'Dây chuyền',fields:[{key:'departmentId',label:'Phòng ban',required:true,source:'departments'},{key:'code',label:'Mã dây chuyền',required:true},{key:'name',label:'Tên dây chuyền',required:true},{key:'description',label:'Mô tả'}]},
 teams:{label:'Tổ sản xuất',fields:[{key:'productionLineId',label:'Dây chuyền',required:true,source:'production-lines'},{key:'code',label:'Mã tổ',required:true},{key:'name',label:'Tên tổ',required:true},{key:'description',label:'Mô tả'}]},
 'machine-types':{label:'Loại máy',fields:[{key:'code',label:'Mã loại máy',required:true},{key:'name',label:'Tên loại máy',required:true},{key:'description',label:'Mô tả'}]},
 machines:{label:'Máy',fields:[{key:'code',label:'Mã máy',required:true},{key:'name',label:'Tên máy',required:true},{key:'serialNumber',label:'Số serial'},{key:'machineTypeId',label:'Loại máy',required:true,source:'machine-types'},{key:'teamId',label:'Tổ sản xuất',required:true,source:'teams'},{key:'installationDate',label:'Ngày lắp đặt',type:'date'},{key:'status',label:'Trạng thái',type:'machine-status'},{key:'description',label:'Mô tả'}]},
 employees:{label:'Nhân viên',fields:[{key:'teamId',label:'Tổ sản xuất',source:'teams'},{key:'code',label:'Mã nhân viên',required:true},{key:'fullName',label:'Họ và tên',required:true},{key:'position',label:'Chức vụ',required:true},{key:'hireDate',label:'Ngày vào làm',type:'date',required:true}]},
 shifts:{label:'Ca làm việc',fields:[{key:'code',label:'Mã ca',required:true},{key:'name',label:'Tên ca',required:true},{key:'startTime',label:'Giờ bắt đầu',type:'time',required:true},{key:'endTime',label:'Giờ kết thúc',type:'time',required:true}]},
 'downtime-reasons':{label:'Lý do dừng máy',fields:[{key:'code',label:'Mã lý do',required:true},{key:'name',label:'Tên lý do',required:true},{key:'reasonType',label:'Loại dừng',type:'reason-type',required:true},{key:'description',label:'Mô tả'}]},
 'quality-error-types':{label:'Loại lỗi chất lượng',fields:[{key:'code',label:'Mã lỗi',required:true},{key:'name',label:'Tên lỗi',required:true},{key:'severity',label:'Mức độ',type:'severity',required:true},{key:'description',label:'Mô tả'}]},
 materials:{label:'Vật tư',fields:[{key:'code',label:'Mã vật tư',required:true},{key:'name',label:'Tên vật tư',required:true},{key:'unit',label:'Đơn vị tính',required:true},{key:'description',label:'Mô tả'}]},
 users:{label:'Tài khoản & phân quyền',fields:[{key:'employeeId',label:'Nhân viên',source:'employees',required:true},{key:'username',label:'Tên đăng nhập',required:true},{key:'password',label:'Mật khẩu ban đầu',type:'password',required:true},{key:'roles',label:'Vai trò',type:'roles',required:true}]}}

export default function AdminMasterPage({section}:{section?:string}){
 const[path,setPath]=useState(section??'factories'),[rows,setRows]=useState<any[]>([]),[options,setOptions]=useState<Record<string,any[]>>({}),[form,setForm]=useState<Record<string,string>>({})
 const[message,setMessage]=useState<{text:string;error:boolean}|null>(null),[busy,setBusy]=useState(false),[editingId,setEditingId]=useState<number|null>(null),[modalOpen,setModalOpen]=useState(false),[resetUser,setResetUser]=useState<any|null>(null),[resetValue,setResetValue]=useState(''),config=configs[path]
 const sources=useMemo(()=>[...new Set(config.fields.flatMap(f=>f.source?[f.source]:[]))],[config])
 useEffect(()=>{if(section&&configs[section])setPath(section)},[section])
 async function load(){try{setRows(await adminApi.list(path))}catch(e){setMessage({text:(e as Error).message,error:true})}}
 useEffect(()=>{setForm({});setEditingId(null);setModalOpen(false);setMessage(null);void load();Promise.all(sources.map(async s=>[s,await adminApi.list(s)]as const)).then(v=>setOptions(Object.fromEntries(v))).catch(e=>setMessage({text:(e as Error).message,error:true}))},[path])
 function openCreate(){setForm({});setEditingId(null);setMessage(null);setModalOpen(true)}
 function edit(row:any){const next:Record<string,string>={};config.fields.forEach(f=>{let value=row[f.key];if(value==null&&f.key.endsWith('Id'))value=row[f.key.slice(0,-2)]?.id;if(Array.isArray(value))value=value.join(',');if(value!=null)next[f.key]=String(value)});setForm(next);setEditingId(row.id);setMessage(null);setModalOpen(true)}
 function closeModal(){if(busy)return;setModalOpen(false);setEditingId(null);setForm({});setMessage(null)}
 async function save(){const missing=!editingId&&config.fields.find(f=>f.required&&!form[f.key]?.trim());if(missing){setMessage({text:`Vui lòng nhập/chọn ${missing.label}.`,error:true});return}if(path==='users'&&!editingId&&form.password.length<8){setMessage({text:'Mật khẩu phải có ít nhất 8 ký tự.',error:true});return}const data=Object.fromEntries(Object.entries(form).filter(([,v])=>v!=='').map(([k,v])=>k.endsWith('Id')?[k,Number(v)]:[k,v.trim()]));setBusy(true);try{if(path==='users'){const selectedRoles=(form.roles??'').split(',').filter(Boolean);if(editingId)await adminApi.updateRoles(editingId,selectedRoles);else{const account=await adminApi.register({employeeId:Number(form.employeeId),username:form.username,password:form.password});await adminApi.updateRoles(account.userId,selectedRoles)}}else if(editingId)await adminApi.update(path,editingId,data);else await adminApi.create(path,{...data,active:true,...(path==='machines'&&!data.status?{status:'IDLE'}:{})});setModalOpen(false);setForm({});setEditingId(null);setMessage({text:`Đã lưu ${config.label} thành công.`,error:false});await load()}catch(e){setMessage({text:(e as Error).message,error:true})}finally{setBusy(false)}}
 async function remove(id:number){if(!confirm(`Bạn có chắc muốn xóa mềm ${config.label} #${id}?`))return;setBusy(true);try{await adminApi.remove(path,id);setMessage({text:`Đã xóa ${config.label} thành công.`,error:false});await load()}catch(e){setMessage({text:(e as Error).message,error:true})}finally{setBusy(false)}}
 async function resetPassword(){if(resetValue.length<8){setMessage({text:'Mật khẩu mới phải có ít nhất 8 ký tự.',error:true});return}setBusy(true);try{await adminApi.resetPassword(resetUser.id,resetValue);const username=resetUser.username;setResetUser(null);setResetValue('');setMessage({text:`Đã đặt lại mật khẩu cho ${username}. Các phiên đăng nhập cũ đã bị vô hiệu hóa.`,error:false})}catch(e){setMessage({text:(e as Error).message,error:true})}finally{setBusy(false)}}
 const roles=['ADMIN','DIRECTOR','FACTORY_MANAGER','DEPARTMENT_MANAGER','FINANCE','PRODUCTION_MANAGER','TEAM_LEADER','EMPLOYEE']
 const enumValues:Record<string,string[]>={'machine-status':['IDLE','RUNNING','STOPPED','MAINTENANCE','BREAKDOWN'],'reason-type':['PLANNED','UNPLANNED'],severity:['LOW','MEDIUM','HIGH','CRITICAL']}
 const visibleFields=config.fields.filter(f=>!(path==='users'&&editingId&&(f.key==='employeeId'||f.key==='password')))
 const fields=<div className="form-grid">{visibleFields.map(f=>f.type==='roles'?<div className="field role-field" key={f.key}><span>Vai trò *</span><div className="role-options">{roles.map(role=>{const checked=(form.roles??'').split(',').includes(role);return <label key={role}><input type="checkbox" checked={checked} onChange={()=>{const current=(form.roles??'').split(',').filter(Boolean);setForm({...form,roles:(checked?current.filter(x=>x!==role):[...current,role]).join(',')})}}/>{role}</label>})}</div></div>:<label className="field" key={f.key}><span>{f.label}{f.required&&!editingId?' *':''}</span>{f.source?<select disabled={path==='users'&&!!editingId} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">-- Chọn {f.label.toLowerCase()} --</option>{(options[f.source]??[]).map(x=><option key={x.id} value={x.id}>{x.code?`${x.code} - `:''}{x.name??x.fullName}</option>)}</select>:f.type&&enumValues[f.type]?<select value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}><option value="">-- Chọn {f.label.toLowerCase()} --</option>{enumValues[f.type].map(v=><option key={v}>{v}</option>)}</select>:<input disabled={path==='users'&&!!editingId} type={f.type??'text'} value={form[f.key]??''} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>}</label>)}</div>
 const normalColumns=config.fields.map(f=>({key:f.key,label:f.label,render:(r:any)=>{if(f.source){const base=f.key.slice(0,-2);return r[`${base}Name`]??r[`${base}Code`]??r[f.key]??'—'}return Array.isArray(r[f.key])?r[f.key].join(', '):String(r[f.key]??'—')}}))
 const userColumns=[{key:'employeeCode',label:'Mã nhân viên'},{key:'employeeName',label:'Nhân viên'},{key:'username',label:'Tên đăng nhập'},{key:'roles',label:'Vai trò',render:(r:any)=>r.roles?.join(', ')??'—'},{key:'enabled',label:'Sử dụng',render:(r:any)=><StatusBadge value={r.enabled}/>},{key:'accountNonLocked',label:'Khóa',render:(r:any)=><StatusBadge value={r.accountNonLocked?'Không khóa':'Đã khóa'}/>}]
 const tableColumns=[{key:'id',label:'ID'},...(path==='users'?userColumns:normalColumns),...(path==='users'?[]:[{key:'active',label:'Trạng thái',render:(r:any)=><StatusBadge value={r.active}/>}]),{key:'action',label:'Thao tác',render:(r:any)=><div className="admin-actions"><button disabled={busy} onClick={()=>edit(r)}>{path==='users'?'Phân quyền':'Sửa'}</button>{path==='users'&&<button disabled={busy} onClick={()=>{setMessage(null);setResetValue('');setResetUser(r)}}>Đặt lại mật khẩu</button>}{path!=='users'&&<button disabled={busy} className="danger-link" onClick={()=>remove(r.id)}>Xóa</button>}{resetUser?.id===r.id&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setResetUser(null)}}><div className="modal reset-password-modal"><div className="admin-modal-header"><div><h2>Đặt lại mật khẩu</h2><p>{r.employeeName} — {r.username}</p></div><button className="modal-close" disabled={busy} onClick={()=>setResetUser(null)}>×</button></div><div className="reset-password-body"><label className="field"><span>Mật khẩu mới *</span><input autoFocus type="password" value={resetValue} onChange={e=>setResetValue(e.target.value)} placeholder="Tối thiểu 8 ký tự"/></label>{message&&<p className={`form-message${message.error?' error':''}`}>{message.text}</p>}</div><div className="form-actions"><button disabled={busy} onClick={()=>setResetUser(null)}>Hủy</button><button className="primary" disabled={busy} onClick={resetPassword}>{busy?'Đang xử lý...':'Xác nhận đặt lại'}</button></div></div></div>}</div>}]
 return <><div className="page-title"><div><h2>Quản trị dữ liệu nhà máy</h2><p>Quản lý đầy đủ danh mục tổ chức, nhân sự, ca làm, máy móc, chất lượng và vật tư</p></div><button className="admin-add-button" onClick={openCreate}>+ Thêm {config.label}</button></div><div className="step-tabs">{Object.entries(configs).map(([k,v])=><button key={k} className={path===k?'active':''} onClick={()=>setPath(k)}>{v.label}</button>)}</div>{message&&!modalOpen&&<p className={`form-message${message.error?' error':''}`}>{message.text}</p>}<Panel title={`Danh sách ${config.label}`}><DataTable rows={rows} columns={tableColumns}/></Panel>{modalOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)closeModal()}}><div className="modal admin-modal"><div className="admin-modal-header"><div><h2>{editingId?'Sửa':'Thêm'} {config.label}</h2><p>{editingId?`Cập nhật bản ghi #${editingId}`:'Nhập đầy đủ thông tin bản ghi mới'}</p></div><button aria-label="Đóng" className="modal-close" onClick={closeModal}>×</button></div>{fields}{message&&<p className={`form-message${message.error?' error':''}`}>{message.text}</p>}<div className="form-actions"><button disabled={busy} onClick={closeModal}>Hủy</button><button className="primary" disabled={busy} onClick={save}>{busy?'Đang xử lý...':editingId?'Lưu thay đổi':'Thêm mới'}</button></div></div></div>}</>
}
